name: Coverage (codecov)

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup rust
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          channel: nightly
          bins: cargo-nextest,cargo-llvm-cov
          components: llvm-tools-preview
      - name: Collect coverage
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov --no-report --doc
          cargo llvm-cov report --doctests --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          files: lcov.info
          use_oidc: true
      - name: Upload to Codecov (junit)
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          files: target/nextest/default/junit.xml
          report_type: test_results
